import "../stlyes/globals.css";
import Navbar from "@components/Navbar";
export const metadata = {
  title: "Honesty Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
