import "../stlyes/globals.css";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Honesty Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-backgroundMain">
        <div>
          <Toaster reverseOrder={false} />
        </div>
        {children}
      </body>
    </html>
  );
}
